#!/bin/sh -eu

# Style enforcement, suitable for use in a pre-commit hook.
#
# Style choices:
#  * two-space indent in scripts, set per .editorconfig
#  * almost-POSIX shell; we demand 'local' be available.
#
# shellcheck source=tools/lib.sh disable=SC2034
. "$(dirname "$0")/lib.sh" "$0" "$@"

cd_to_repo_root

for F in tools/*; do
  verbose "checking $F"
  base="$(basename "$F")"

  case "$base" in
  lib.sh)
    # SC1008 because using #!/bin/echo
    # SC2034 because plenty of unused variables set for sourcers
    # SC2039 because we use 'local'
    # SC2096 because using #!/bin/echo
    shellcheck -e SC1008,SC2034,SC2039,SC2096 "$F" || bump_warn_count
    ;;
  *)
    # SC2039 because we use 'local'
    shellcheck -e SC2039 -x "$F" || bump_warn_count
    ;;
  esac

  out="$(shfmt -ln posix -i 2 -l "$F")"
  if [ -n "$out" ]; then
    warn_multi "shfmt: $out" \
      "see: shfmt -ln posix -i 2 -d '$F'" \
      "fix: shfmt -ln posix -i 2 -w '$F'"
  fi

done

report_exit -0
